[workspace]
authors = ["Byron"]
channels = ["conda-forge"]
name = "Advent-of-Code-Python"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
run-day1 = 'python puzzles/Day1/main.py'
run-day2 = "python puzzles/Day2/main.py"
run-day3 = "python puzzles/Day3/main.py"

[dependencies]
python = "3.14.*"
